language: python


python:
    - "3.6"

sudo: required

services:
    - docker

notifications:
  email:
    recipients:
      - qzhang@anl.gov
    on_success: never # default: change
    on_failure: always # default: always

branches:
  only:
    - master

before_install:
    - docker version
    - python --version

install:
    # TODO need to switch to GHA and actually test this module
    - git clone https://github.com/kbase/jars
    - git clone https://github.com/kbase/kb_sdk
    - cd kb_sdk
    - make bin
    - make sdkbase
    - docker images
    - export PATH=$(pwd)/bin:$PATH
    - cd ../
    - git clone https://github.com/kbaseapps/kb_SPAdes.git
    # Uh, what
    - cd kb_SPAdes
    # run the kb-sdk test command once to build test_local dir and populate the .ignore files
    - kb-sdk test -s || true

script:
    - kb-sdk validate

